#!/bin/zsh

#
# consts
#
BISTDIR=$HOME/.bist
BISTDIR_BIN=$BISTDIR/bin
BISTDIR_REPOS=$BISTDIR/repos
GIST_URL=https://gist.github.com/

#
# usage
#
function usage() {
    cat <<EOT
USAGE:
    bist [COMMAND] [ARGS]*

COMMAND:
    list
        listup local gist repository.

    reconstruction-script
        put environment re-construction script.

    show [GIST_NUMBER | FILENAME]
        cat gist file.

    install [GIST_NUMBER]
        clone or pull gist files.

    update
        update all local gist files.

    rehash
        symbolic link to bin

    rm [GIST_NUMBER]
        remove gist repository.
EOT

    exit 0
}

#
# bist chmod [gist_num]
#
function bist_chmod() {
  find $1 -maxdepth 1 -type f | xargs chmod a+x
}

#
# bist install [gist_num]
#
function bist_install() {
    if [ $# -lt 1 ]; then
        usage
    fi
    gistnum=$1
    clonedir=$BISTDIR_REPOS/$gistnum

    if [ ! -d $clonedir ]; then
        git clone "${GIST_URL}${gistnum}.git" $clonedir > /dev/null 2>&1
    else
        cd $clonedir
        git pull --rebase > /dev/null 2>&1
        cd - > /dev/null
    fi

    bist_chmod $clonedir
}

#
# bist update
#
function bist_update() {
    for d in `find $BISTDIR_REPOS -mindepth 1 -maxdepth 1 -type d`
    do
        gist_num=`basename $d`
        echo -n "pulling $gist_num ..."
        bist_install $gist_num
        echo done
    done
}

#
# bist show [num | file]
#
function bist_show() {
    if [ $# -lt 1 ]; then
        usage
    fi

    num_or_file=$1
    isnum=`echo $num_or_file | egrep "^[0-9]+$"`

    file=""
    if [ $isnum -a -d "$BISTDIR_REPOS/$num_or_file" ]; then
        file=`find $BISTDIR_REPOS/$num_or_file -type f -depth 1 | head -1`
    else
        file=`find $BISTDIR_REPOS -type f -depth 2 | grep $num_or_file | head -1`
    fi

    if [ "$file" -a -f "$file" ]; then
        cat $file
    else
        echo "$file not found." >&2
        exit 0
    fi
}

#
# bist list [num]?
#
function bist_list() {
  find $BISTDIR_REPOS -maxdepth 2 -type f | sed -e "s|^${BISTDIR_REPOS}/||" -e 's|/|	|g'
}

function bist_reconstruction_script() {
  find $BISTDIR_REPOS -maxdepth 2 -type f | sed -e "s|^${BISTDIR_REPOS}/||" -e 's|/| # |g' -e 's/^/bist install /'
}

#
# bist rehash
#
function bist_rehash() {
  mkdir -p "$BISTDIR_BIN"
  find $BISTDIR_REPOS -maxdepth 2 -type f -exec ln -sf {} ${BISTDIR_BIN}/ \;
}

#
# bist rm [num]
#
function bist_rm () {
    if [ $# -ne 1 ]; then
        usage
    fi

    gistdir=$BISTDIR_REPOS/$2
    if [ -d $gistdir ]; then
        echo $gistdir
        rm -rf $gistdir
    fi
}

function bist_init () {
    mkdir -p $BISTDIR_REPOS
    mkdir -p $BISTDIR_BIN
}

# -----------------------------------
# main
# -----------------------------------
command=$1
shift

case $command in
    "list" | "l" ) bist_list $* ;;
    "reconstruction-script" ) bist_reconstruction_script $* ;;
    "show" | "s" ) bist_show $* ;;
    "rehash" | "r" ) bist_rehash ;;
    "rm" ) bist_rm $* ;;
    "install" | "i" ) bist_install $* ;;
    "init" ) bist_init $* ;;
    "update" | "u" ) bist_update $* ;;
    *) usage ;;
esac
